### ISSUE TITLE
Bug shapely sur Linux Distro

### ISSUE THREAD

**Issue by davidmaignan** [LAEQ/q3m#17]
La version de shapely sur Linux fait planter QGis.

L'exécution du code suivant dans la console de QGIS.
```python
from shapely.geometry import Point, LineString
LineString([Point(0, 0), Point(1, 1)]).wkt

>> QGIS crash

```
Dans un terminal:
```python
>>> from shapely.geometry import Point, LineString
>>> LineString([Point(0, 0), Point(1, 1)]).wkt
'LINESTRING (0 0, 1 1)'
```

J'ai pu apercevoir l'erreur suivante (avant plantage):
`
Traceback (most recent call last):
 ...
    geom = QgsGeometry().fromWkt(obj["geometry"].wkt)
  File "$HOME/.local/lib/python3.6/site-packages/shapely/geometry/base.py", line 375, in wkt
    return WKTWriter(lgeos).write(self)
  File "$HOME/.local/lib/python3.6/site-packages/shapely/geos.py", line 403, in write
    return text.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xde in position 1: ordinal not in range(128)
`
Pour info:
> terminal
Python 3.6.12
Shapely: 1.7.1

**Comment by davidmaignan** [comment]
Le problème n'apparait qu'à partir de la version  >= 1.6
